(function(){"function"!==typeof Function.prototype.bind&&(Function.prototype.bind=function(a){function b(){return f.apply(this instanceof d&&a?this:a,c.concat(Array.prototype.slice.call(arguments)))}function d(){}if("function"!==typeof this)throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");var c=Array.prototype.slice.call(arguments,1),f=this;d.prototype=this.prototype;b.prototype=new d;return b});
(function(a){for(var b=0,d=["ms","moz","webkit","o"],c=0;c<d.length&&!a.requestAnimationFrame;++c)a.requestAnimationFrame=a[d[c]+"RequestAnimationFrame"],a.cancelAnimationFrame=a[d[c]+"CancelAnimationFrame"]||a[d[c]+"CancelRequestAnimationFrame"];a.requestAnimationFrame||(a.requestAnimationFrame=function(c){var d=(new Date).getTime(),h=Math.max(0,16-(d-b)),e=a.setTimeout(function(){c(d+h)},h);b=d+h;return e});a.cancelAnimationFrame||(a.cancelAnimationFrame=function(a){clearTimeout(a)})})(window);var s={a:{R:[[/projects\/?(.*)/,"projects"],[/tag\/(.+)/,"tag"],[/salary-calc/,"salary-calc"],[/fractal\/?(.*)/,"fractal"],[/test-buttons\/?(.*)/,"test-buttons"],[/^dashboard\/?(.*)/,"dashboard"],[/^pp\/?(.*)/,"pp"],[/^bb\/?(.*)/,"bb"],[/^cv\/?(.*)/,"cv",["d3"]],[/(.*)/,""]],map:{d3:"//cdnjs.cloudflare.com/ajax/libs/d3/3.4.13/d3.min.js"},za:[/^\/blog\//],eb:"//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome",m:{"":{name:"Indamix",items:[["About","about"],["Contacts","contacts"],["Projects",
"projects"],["Apps","apps"]]},about:{name:"About",content:[{size:20,x:190,y:-75,s:"Front End Engineer"},{size:20,x:80,y:45,s:"Startup Co-founder"},{size:20,x:190,y:45,s:"Open-source Contributor"}]},contacts:{name:"Contacts",items:[["Twitter","https://twitter.com/indamix"],["GitHub","https://github.com/Indamix"],["LinkedIn","http://www.linkedin.com/in/indamix"],["Skype","skype:indamix.online?call"]]},apps:{name:"Apps",items:[["Mandelbrot","fractal"],["FrEd","https://indamix.github.io/fred/"]]}}}};s.a&&(s=s.a);var u={};u.a=u={};function aa(){return window.W?location.href:"https://indamix.github.io/"+location.hash}aa.pa=function(){return window.W?"":"https://indamix.github.io"};u.fb=aa;
u.Pa=function(){var a=window._gaq=[];a.push(["_setAccount","UA-3667863-9"]);a.push(["_trackPageview"]);a=document.createElement("script");a.type="text/javascript";a.async=!0;a.src=("https:"==document.location.protocol?"https://ssl":"http://www")+".google-analytics.com/ga.js";var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)};u.na=function(a){return $('<link rel="stylesheet" href="'+a+'.css"/>').appendTo(document.head)};u.xb=function(){$('<link href="'+u.aa()+'i/favicon.ico" rel="icon" type="image/x-icon">').appendTo(document.head)};
u.aa=function ba(){if(ba.prefix)return ba.prefix;var b=document.getElementsByTagName("script"),b=b[b.length-1].src.replace(/static\/.*/,"");return ba.prefix=b};u.Sa=function(a){var b;return function(){var d=this,c=arguments;clearTimeout(b);b=setTimeout(function(){b=null;a.apply(d,c)},200)}};u.hb=function(a){setTimeout(a,0)};u.a&&(u=u.a);var v={};
v.a={projects:[{name:"real-shadow",t:"Real Shadow",url:"http://indamix.github.io/real-shadow/",ext:"jpg",desc:"Photorealistic Shadows of any shape",list:[["camera","Casts photorealistic shadows of any shape"],["eye","Perfect for eye-catching demos and landing pages"],["code-fork",'<a href="https://github.com/Indamix/real-shadow/stargazers">1000+</a> GitHub Stars, <a href="https://github.com/Indamix/real-shadow/network">100+</a> GitHub Forks'],["puzzle-piece","Behaves as CommonJS or AMD module or jQuery plugin"]],tags:["Open-source",
"JavaScript","HTML5","CSS3","Desktop"]},{name:"ctrader",t:"cTrader",url:"http://ct.spotware.com/",ext:"png",desc:"Forex Trading Web Application",list:[["tachometer","Rapid and responsive"],["sitemap","Code divided into reusable modules"],["mobile","Available for both desktop and mobile platform"],["globe","Internationalized"]],tags:"JavaScript OOP CommonJS HTML5 CSS3 SASS SVG Canvas WebSocket localStorage Polyfills Desktop Mobile".split(" ")},{name:"rutwit",t:"RuTwit Startup",Gb:"Sold",url:"http://rutwit.ru",ext:"jpg",desc:"Realtime Social Service with Geolocation and Media Embeds",list:[["dollar","Sold to Mail.Ru Group (LSE:MAIL) in Dec 2011"],
["picture-o","Share images, pictures and music from many services"],["external-link","Import and export to external services"],["map-marker","Find people and messages given the location"]],tags:"JavaScript HTML5 CSS3 Realtime Geolocation Desktop Mobile Startup".split(" ")},{name:"xdrink",t:"XDrink",url:"http://xdrink.ru",ext:"jpg",desc:"Cocktails Infographics and Recipes Application",list:[["glass","See what cocktails can be made given the ingredients"],["sort-amount-asc","Cocktails are sorted by complexity and strength"]],
tags:["JavaScript","HTML5","CSS3","Desktop","Mobile"]}],path:u.aa()};v.a&&(v=v.a);/*
 FastClick: polyfill to remove click delays on browsers with touch UIs.

 @codingstandard ftlabs-jsv2
 @copyright The Financial Times Limited [All Rights Reserved]
 @license MIT License (see LICENSE.txt)
*/
var z={};
(function(){function a(e,b){function c(a,e){return function(){return a.apply(e,arguments)}}var f;b=b||{};this.l=!1;this.T=0;this.e=null;this.ya=this.La=this.Ka=0;this.Ja=b.Ja||10;this.ka=b.ka||200;this.Ga=b.Ga||700;if(!a.ib(e)){for(var g="onMouse onClick onTouchStart onTouchMove onTouchEnd onTouchCancel".split(" "),h=0,t=g.length;h<t;h++)this[g[h]]=c(this[g[h]],this);d&&(e.addEventListener("mouseover",this.P,!0),e.addEventListener("mousedown",this.P,!0),e.addEventListener("mouseup",this.P,!0));e.addEventListener("click",
this.kb,!0);e.addEventListener("touchstart",this.pb,!1);e.addEventListener("touchmove",this.ob,!1);e.addEventListener("touchend",this.nb,!1);e.addEventListener("touchcancel",this.mb,!1);Event.prototype.stopImmediatePropagation||(e.removeEventListener=function(a,b,c){var d=Node.prototype.removeEventListener;"click"===a?d.call(e,a,b.va||b,c):d.call(e,a,b,c)},e.addEventListener=function(a,b,c){var d=Node.prototype.addEventListener;"click"===a?d.call(e,a,b.va||(b.va=function(a){a.rb||b(a)}),c):d.call(e,
a,b,c)});"function"===typeof e.onclick&&(f=e.onclick,e.addEventListener("click",function(a){f(a)},!1),e.onclick=null)}}var b=0<=navigator.userAgent.indexOf("Windows Phone"),d=0<navigator.userAgent.indexOf("Android")&&!b,c=/iP(ad|hone|od)/.test(navigator.userAgent)&&!b,f=c&&/OS 4_\d(_\d)?/.test(navigator.userAgent),g=c&&/OS [6-7]_\d/.test(navigator.userAgent),h=0<navigator.userAgent.indexOf("BB10");a.prototype.Aa=function(a){switch(a.nodeName.toLowerCase()){case "button":case "select":case "textarea":if(a.disabled)return!0;
break;case "input":if(c&&"file"===a.type||a.disabled)return!0;break;case "label":case "iframe":case "video":return!0}return/\bneedsclick\b/.test(a.className)};a.prototype.gb=function(a){switch(a.nodeName.toLowerCase()){case "textarea":return!0;case "select":return!d;case "input":switch(a.type){case "button":case "checkbox":case "file":case "image":case "radio":case "submit":return!1}return!a.disabled&&!a.readOnly;default:return/\bneedsfocus\b/.test(a.className)}};a.prototype.Fa=function(a,b){var c,
d;document.activeElement&&document.activeElement!==a&&document.activeElement.blur();d=b.changedTouches[0];c=document.createEvent("MouseEvents");c.initMouseEvent(this.Ua(a),!0,!0,window,1,d.screenX,d.screenY,d.clientX,d.clientY,!1,!1,!1,!1,0,null);c.Za=!0;a.dispatchEvent(c)};a.prototype.Ua=function(a){return d&&"select"===a.tagName.toLowerCase()?"mousedown":"click"};a.prototype.focus=function(a){var b;c&&a.setSelectionRange&&0!==a.type.indexOf("date")&&"time"!==a.type&&"month"!==a.type?(b=a.value.length,
a.setSelectionRange(b,b)):a.focus()};a.prototype.Bb=function(a){var b,c;b=a.L;if(!b||!b.contains(a)){c=a;do{if(c.scrollHeight>c.offsetHeight){b=c;a.L=c;break}c=c.parentElement}while(c)}b&&(b.Wa=b.scrollTop)};a.prototype.ta=function(a){return a.nodeType===Node.TEXT_NODE?a.parentNode:a};a.prototype.pb=function(a){var b,d,g;if(1<a.targetTouches.length)return!0;b=this.ta(a.target);d=a.targetTouches[0];if(c){g=window.getSelection();if(g.rangeCount&&!g.isCollapsed)return!0;if(!f){if(d.identifier&&d.identifier===
this.ya)return a.preventDefault(),!1;this.ya=d.identifier;this.Bb(b)}}this.l=!0;this.T=a.timeStamp;this.e=b;this.Ka=d.pageX;this.La=d.pageY;a.timeStamp-this.xa<this.ka&&a.preventDefault();return!0};a.prototype.zb=function(a){a=a.changedTouches[0];var b=this.Ja;return Math.abs(a.pageX-this.Ka)>b||Math.abs(a.pageY-this.La)>b?!0:!1};a.prototype.ob=function(a){if(!this.l)return!0;if(this.e!==this.ta(a.target)||this.zb(a))this.l=!1,this.e=null;return!0};a.prototype.Ya=function(a){return void 0!==a.control?
a.control:a.htmlFor?document.getElementById(a.htmlFor):a.querySelector("button, input:not([type=hidden]), keygen, meter, output, progress, select, textarea")};a.prototype.nb=function(a){var b,k,h=this.e;if(!this.l)return!0;if(a.timeStamp-this.xa<this.ka)return this.qa=!0;if(a.timeStamp-this.T>this.Ga)return!0;this.qa=!1;this.xa=a.timeStamp;b=this.T;this.l=!1;this.T=0;g&&(k=a.changedTouches[0],h=document.elementFromPoint(k.pageX-window.pageXOffset,k.pageY-window.pageYOffset)||h,h.L=this.e.L);k=h.tagName.toLowerCase();
if("label"===k){if(b=this.Ya(h)){this.focus(h);if(d)return!1;h=b}}else if(this.gb(h)){if(100<a.timeStamp-b||c&&window.top!==window&&"input"===k)return this.e=null,!1;this.focus(h);this.Fa(h,a);c&&"select"===k||(this.e=null,a.preventDefault());return!1}if(c&&!f&&(b=h.L)&&b.Wa!==b.scrollTop)return!0;this.Aa(h)||(a.preventDefault(),this.Fa(h,a));return!1};a.prototype.mb=function(){this.l=!1;this.e=null};a.prototype.P=function(a){return this.e&&!a.Za&&a.cancelable?!this.Aa(this.e)||this.qa?(a.stopImmediatePropagation?
a.stopImmediatePropagation():a.rb=!0,a.stopPropagation(),a.preventDefault(),!1):!0:!0};a.prototype.kb=function(a){if(this.l)return this.e=null,this.l=!1,!0;if("submit"===a.target.type&&0===a.detail)return!0;a=this.P(a);a||(this.e=null);return a};a.ib=function(a){var b,c;if("undefined"===typeof window.ontouchstart)return!0;if(c=+(/Chrome\/([0-9]+)/.exec(navigator.userAgent)||[,0])[1])if(d){if((b=document.querySelector("meta[name=viewport]"))&&(-1!==b.content.indexOf("user-scalable=no")||31<c&&document.documentElement.scrollWidth<=
window.outerWidth))return!0}else return!0;return h&&(b=navigator.userAgent.match(/Version\/([0-9]*)\.([0-9]*)/),10<=b[1]&&3<=b[2]&&(b=document.querySelector("meta[name=viewport]"))&&(-1!==b.content.indexOf("user-scalable=no")||document.documentElement.scrollWidth<=window.outerWidth))||"none"===a.style.msTouchAction||"manipulation"===a.style.Ia||27<=+(/Firefox\/([0-9]+)/.exec(navigator.userAgent)||[,0])[1]&&(b=document.querySelector("meta[name=viewport]"))&&(-1!==b.content.indexOf("user-scalable=no")||
document.documentElement.scrollWidth<=window.outerWidth)?!0:"none"===a.style.Ia||"manipulation"===a.style.Ia?!0:!1};a.Qa=function(b,c){return new a(b,c)};z.a=a.Qa;z.a.Db=a})();z.a&&(z=z.a);var ca={};
function da(a){function b(a){return"function"===typeof a}function d(a){return a.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,"\\$&")}function c(b,c){function e(a){"string"===typeof a&&(a=a.split(I,2));if(!p(a)||2!==a.length)throw Error("Invalid tags: "+a);qa=RegExp(d(a[0])+"\\s*");J=RegExp("\\s*"+d(a[1]));ua=RegExp("\\s*"+d("}"+a[1]))}if(!b)return[];var l=[],k=[],ga=[],t=!1,ha=!1,qa,J,ua;e(c||a.yb);for(var r=new h(b),w,q,y,B;!r.Va();){w=r.k;if(y=r.r(qa)){B=0;for(var K=y.length;B<K;++B)if(q=y.charAt(B),m.call(n,
q)?ha=!0:ga.push(k.length),k.push(["text",q,w,w+1]),w+=1,"\n"===q){if(t&&!ha)for(;ga.length;)delete k[ga.pop()];else ga=[];ha=t=!1}}if(!r.q(qa))break;t=!0;q=r.q(oa)||"name";r.q(A);"="===q?(y=r.r(ea),r.q(ea),r.r(J)):"{"===q?(y=r.r(ua),r.q(na),r.r(J),q="&"):y=r.r(J);if(!r.q(J))throw Error("Unclosed tag at "+r.k);B=[q,y,w,r.k];k.push(B);if("#"===q||"^"===q)l.push(B);else if("/"===q){q=l.pop();if(!q)throw Error('Unopened section "'+y+'" at '+w);if(q[1]!==y)throw Error('Unclosed section "'+q[1]+'" at '+
w);}else"name"===q||"{"===q||"&"===q?ha=!0:"="===q&&e(y)}if(q=l.pop())throw Error('Unclosed section "'+q[1]+'" at '+r.k);return g(f(k))}function f(a){for(var b=[],c,d,e=0,g=a.length;e<g;++e)if(c=a[e])"text"===c[0]&&d&&"text"===d[0]?(d[1]+=c[1],d[3]=c[3]):(b.push(c),d=c);return b}function g(a){for(var b=[],c=b,d=[],e,g=0,h=a.length;g<h;++g)switch(e=a[g],e[0]){case "#":case "^":c.push(e);d.push(e);c=e[4]=[];break;case "/":c=d.pop();c[5]=e[2];c=0<d.length?d[d.length-1][4]:b;break;default:c.push(e)}return b}
function h(a){this.f=a;this.k=0}function e(a,b){this.view=null==a?{}:a;this.C={".":this.view};this.parent=b}function l(){this.C={}}var k=Object.prototype.toString,p=Array.isArray||function(a){return"[object Array]"===k.call(a)},m=RegExp.prototype.test,n=/\S/,t={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;","/":"&#x2F;"},A=/\s*/,I=/\s+/,ea=/\s*=/,na=/\s*\}/,oa=/#|\^|\/|>|\{|&|=|!/;h.prototype.Va=function(){return""===this.f};h.prototype.q=function(a){a=this.f.match(a);if(!a||0!==a.index)return"";
a=a[0];this.f=this.f.substring(a.length);this.k+=a.length;return a};h.prototype.r=function(a){a=this.f.search(a);var b;switch(a){case -1:b=this.f;this.f="";break;case 0:b="";break;default:b=this.f.substring(0,a),this.f=this.f.substring(a)}this.k+=b.length;return b};e.prototype.push=function(a){return new e(a,this)};e.prototype.N=function(a){var c=this.C,d;if(a in c)d=c[a];else{for(var e=this,g,h;e;){if(0<a.indexOf("."))for(d=e.view,g=a.split("."),h=0;null!=d&&h<g.length;)d=d[g[h++]];else"object"==
typeof e.view&&(d=e.view[a]);if(null!=d)break;e=e.parent}c[a]=d}b(d)&&(d=d.call(this.view));return d};l.prototype.ra=function(){this.C={}};l.prototype.parse=function(a,b){var d=this.C,e=d[a];null==e&&(e=d[a]=c(a,b));return e};l.prototype.c=function(a,b,c){var d=this.parse(a);return this.p(d,b instanceof e?b:new e(b),c,a)};l.prototype.p=function(c,d,e,g){function h(a){return l.c(a,d,e)}for(var f="",l=this,k,m,n=0,t=c.length;n<t;++n)switch(k=c[n],k[0]){case "#":m=d.N(k[1]);if(!m)continue;if(p(m))for(var r=
0,w=m.length;r<w;++r)f+=this.p(k[4],d.push(m[r]),e,g);else if("object"===typeof m||"string"===typeof m)f+=this.p(k[4],d.push(m),e,g);else if(b(m)){if("string"!==typeof g)throw Error("Cannot use higher-order sections without the original template");m=m.call(d.view,g.slice(k[3],k[5]),h);null!=m&&(f+=m)}else f+=this.p(k[4],d,e,g);break;case "^":m=d.N(k[1]);if(!m||p(m)&&0===m.length)f+=this.p(k[4],d,e,g);break;case ">":if(!e)continue;m=b(e)?e(k[1]):e[k[1]];null!=m&&(f+=this.p(this.parse(m),d,e,m));break;
case "&":m=d.N(k[1]);null!=m&&(f+=m);break;case "name":m=d.N(k[1]);null!=m&&(f+=a.escape(m));break;case "text":f+=k[1]}return f};a.name="mustache.js";a.version="1.0.0";a.yb=["{{","}}"];var K=new l;a.ra=function(){return K.ra()};a.parse=function(a,b){return K.parse(a,b)};a.c=function(a,b,d){return K.c(a,b,d)};a.Lb=function(d,c,e,f){d=a.c(d,c,e);if(b(f))f(d);else return d};a.escape=function(a){return String(a).replace(/[&<>"'\/]/g,function(a){return t[a]})};a.Eb=h;a.Cb=e;a.Fb=l}
"object"===typeof ca&&ca?da(ca):"function"===typeof define&&define.Hb?define(["exports"],da):da({});var C={};
(function(a){function b(a){if(!Array.isArray(a)||2>a.length||"function"!==typeof a[a.length-1])return!1;for(var b=a.length-1;b--;)if("string"!==typeof a[b])return!1;return!0}function d(a){if(!b(a))return a;var d=a.pop();return function(){for(var b=Array(a.length),c=b.length;c--;)b[c]=g[a[c]];return d.apply(this,b.concat(h.call(arguments)))}}function c(a){if(2===arguments.length&&"string"===typeof a)return c.F(a,arguments[1]);if("string"===typeof a)return g[a];if(Array.isArray(a)){for(var b=Array(a.length),
f=a.length;f--;){if("string"!==typeof a[f])return d(a);b[f]=g[a[f]]}return b}return a}function f(){}var g={},h=Array.prototype.slice;c.extend=function(b){var c=this,g;"function"===typeof b?(g=b,b=b.prototype):(b.constructor===Object&&(b.constructor=function(){c.apply(this,arguments)}),g=d(b.constructor));f.prototype=c.prototype;g.prototype=new f;f.prototype=a;for(var h=Object.getOwnPropertyNames(b),m=h.length;m--;){var n=Object.getOwnPropertyDescriptor(b,h[m]);n.value=d(n.value);Object.defineProperty(g.prototype,
h[m],n)}g.extend=c.extend;g.F=c.F;g.Ma=c.Ma;g.reset=c.reset;g.prototype.constructor=g;g.Kb=c.prototype;return g};c.F=function(b,c){if("object"===typeof b&&c===a)for(var d in b)b.hasOwnProperty(d)&&(g[d]=b[d]);else g[b]=c;return this};c.Ma=function(a){delete g[a];return this};c.reset=function(){g={};return this};C.a=c})();C.a&&(C=C.a);var D={},fa=Array.prototype.slice,ja=C.extend({constructor:function(){this.A={}},on:function ia(b,d,c,f){if(~b.indexOf(" ")){for(var g=fa.call(arguments),h=b.split(" "),e=0;e<h.length;++e)g[0]=h[e],ia.apply(this,g);return this}"function"===typeof d&&(f=c,c=d,d=void 0);g=this.A;(g[b]||(g[b]=[])).push([c,f,d]);return this},off:function(a,b){if(0===arguments.length)return this.A={},this;if(1===arguments.length)return this.A[a]=[],this;for(var d=this.A[a]||[],c=0;c<d.length;++c)d[c][0]===b&&d.splice(c,
1);return this},trigger:function(a){for(var b=this.A,b=b[a]||(b[a]=[]),d=fa.call(arguments,1),c=[],f=0,g=b.length;f<g;++f)c.push(b[f][0].apply(b[f][1]||this,"undefined"===typeof b[f][2]?d:d.concat([b[f][2]])));return c}});D.a=ja;D.a&&(D=D.a);var E={},ka=D,la={i:function(){this.$.appendTo(document.body)},s:function(){this.$.detach()}};function ma(a,b){return function(){!1!==a.apply(this,arguments)&&b.apply(this,arguments)}}var pa=ka.extend(la).extend({constructor:function(a){ka.call(this);a=a||{};this.b=this.$=a.b||$("<div/>");this.update()},update:["tpl",function(a,b,d){this.b.html(a(d||this.v,b,this.Ib))}]});
pa.constructor=function(a){if(!a["\u5350"]){a["\u5350"]=1;for(var b in la)"constructor"!==b&&(a[b]=void 0===a[b]?la[b]:ma(a[b],la[b]))}};E.a=pa;E.a&&(E=E.a);var F={},ra=E,sa=ra.extend({constructor:function(){ra.call(this);this.b.on("click","a.fa",this.M.bind(this));if(!document.getElementById(this.id)){var a=document.createElement("script");a.id=this.id;a.src=this.src;document.head.appendChild(a)}}});F.a=sa;F.a&&(F=F.a);var G={};G.a=F.extend({id:"facebook-jssdk",src:"//connect.facebook.net/en_US/all.js#xfbml=1",v:'<a class="fa fa-facebook"></a>',ea:'<div class="fb-like" data-href="{{url}}" data-layout="box_count" data-action="like" data-show-faces="true" data-share="true"></div>',M:["location","tpl",function(a,b){this.b.html(b(this.ea),{url:a()});window.FB&&window.FB.XFBML.parse()}]});G.a&&(G=G.a);var H={};H.a=F.extend({id:"twitter-wjs",src:"//platform.twitter.com/widgets.js",v:'<a class="fa fa-twitter"></a>',M:["location","loader",function(a,b){window.twttr&&(this.b.empty(),window.twttr.widgets.createShareButton(a(),this.b[0],$.noop,{text:b.title,size:"large"}))}]});H.a&&(H=H.a);var L={},ta=E,va=H,wa=G;
L.a=ta.extend({constructor:["router","loader",function(a,b,d){ta.call(this,d);this.b.on("click",this.toggle.bind(this));this.h=!1;a.on("route",this.hide,this);b.on("title",this.Na,this);this.ca=this.ca.bind(this)}],toggle:function(){this.h?this.hide():this.show()},Ra:function(){this.g=$(this.ea).append((this.Ab=new va).b,(this.Xa=new wa).b);this.la=this.g.find(".url");this.la.on("focus",function(){var a=this;setTimeout(function(){a.setSelectionRange(0,1E3)},0)})},show:function(){!this.g&&this.Ra();
this.g.appendTo(document.body);xa(this.g);this.b.addClass("active");this.h=!0;this.reset();this.Na()},hide:function(){this.h&&(this.g.removeClass("shown"),setTimeout(this.ca,500),this.b.removeClass("active"),this.h=!1)},ca:function(){this.h||this.g.detach()},reset:["location",function(a){this.g&&(this.la.val(a()),this.Ab.update(),this.Xa.update())}],Na:["loader",function(a){a="Indamix"===a.title?"":a.title;this.b.attr("title","Share "+a);this.g&&this.g.find(".header b").html(a)}],ea:'<div class="sharePanel"><h1 class="header">Share <b></b></h1><label class="byLink">Share by Link <input class="url"/></label></div>'});
function xa(a){setTimeout(function(){a.addClass("shown")},0)}L.a&&(L=L.a);var M={},ya=E,za=L,Aa=ya.extend({constructor:["loader","location",function(a,b,d){ya.call(this,d);var c=new za({b:$('<a class="btn fa fa-share"></a>')});this.I=this.b.find(".panel:first");this.Z=d.Z;this.items={home:$('<a href="'+b.pa()+'/#/" class="btn fa fa-home"></a>'),share:c.b};a.on("init",this.set,this)}],set:function(a){this.I.children().detach();this.b.children().not(this.I).detach();a=a.sb||this.Z;for(var b,d=0;d<a.length;++d){var c=a[d];"string"===typeof c?this.I.append(this.items[c]):(b=
b||$('<div class="panel"></div>').insertAfter(this.I),b.append(c))}},v:'<div class="panel about"></div>'});M.a=Aa;M.a&&(M=M.a);var N={};N.a=D.extend({constructor:function(a){this.url=a},get:function(){return this.ub||(this.ub=$.get(this.url))}});N.a&&(N=N.a);var O={},Ba=E,Ca=N;
O.a=Ba.extend({constructor:function(a){Ba.call(this,{b:a});this.qb=new Ca("/posts.json");this.ia=this.ia.bind(this)},v:'<h1>Posts tagged <b>{{tag}}</b></h1>{{#posts}}<div class="post"><p class="meta">{{date}}</p><a href="{{link}}">{{title}}</a></div>{{/posts}}',css:!1,title:function(a){a("Posts tagged "+this.ja)},i:function(a){this.ja=a;this.qb.get().done(this.ia)},ia:function(a){for(var b=[],d=0;d<a.length;++d){var c=a[d];-1!==c.tags.indexOf(this.ja)&&b.push(c)}this.update({tag:this.ja,posts:b})}});
O.a&&(O=O.a);var P={};
P.a=C.extend({constructor:function(a){this.d=a;this.frame=this.frame.bind(this)},vb:function(a,b,d,c,f){this.G=a;this.K=b;this.duration=d;this.direction=c;this.Oa=f;this.startTime=+new Date;this.timer=requestAnimationFrame(this.frame);this.wa=!0},frame:function(){var a=(new Date-this.startTime)/this.duration;1<=a?(a=1,this.wa=!1):(a*=a,this.timer=requestAnimationFrame(this.frame));var b=this.G.width,a=a*b|0;switch(this.direction){case 0:this.d.putImageData(this.G,0,a);this.d.putImageData(this.K,0,
a-b);break;case 1:this.d.putImageData(this.G,-a,0);this.d.putImageData(this.K,b-a,0);break;case 2:this.d.putImageData(this.G,a,0);this.d.putImageData(this.K,a-b,0);break;case 3:this.d.putImageData(this.G,0,-a),this.d.putImageData(this.K,0,b-a)}this.Oa()}});P.a&&(P=P.a);var Q={};
Q.a=C.extend({constructor:function(a,b){this.canvas=a;this.d=a.getContext("2d");this.set(b)},getData:function(){return this.d.getImageData(0,0,this.canvas.width,this.canvas.height)},c:function(a){var b,d;a?a=this.ba(b=a.x,d=a.y):(b=d=NaN,a=-1);for(var c=this.d,f=this.items,g=this.getData(),h=g.data,e,l,k,p,m,n=0;n<h.length;n+=4){e=(n>>2)%256;l=n-e>>10;k=this.ba(e,l);k=f&&f[k]?a===k:a===k&&4===k;p=64-Math.abs(b-e)-Math.abs(d-l)<<1;0>p&&(p=0);switch(this.position){case 0:m=e+p;e=255-l>>1;l=p;break;
case 1:m=255;e>>=1;l-=p;break;case 2:m=p;e=p+255-e>>1;l+=p;break;case 3:m=e+p;e=l>>1;l=255;break;default:m=e,e=p,l-=p}k&&(m+=50,e+=50,l+=50);h[n]=m;h[n+1]=e;h[n+2]=l;h[n+3]=255}c.putImageData(g,0,0);c.fillStyle="#fff";c.save();c.rotate(Math.PI/4);if(this.content)for(n=0;h=this.content[n];n++){c.save();h.size&&(c.font="500 "+h.size+"px Helvetica Neue, Helvetica, Arial, sans-serif");b=c;d=h.x;g=h.y;h=h.s.split(" ");l="";for(k=0;k<h.length;k++)m=l+h[k]+" ",50<b.measureText(m).width&&0<k?(b.fillText(l,
d,g),l=h[k]+" ",g+=20):l=m;b.fillText(l,d,g);c.restore()}c.restore();c.save();c.textAlign="center";c.save();c.rotate(Math.PI/4);this.ua&&(c.font="500 24px Helvetica Neue, Helvetica, Arial, sans-serif",c.fillStyle=4===a?"#000":"#fff",c.fillText("BACK",48,9));c.globalCompositeOperation="overlay";c.font="500 48px Helvetica Neue, Helvetica, Arial, sans-serif";c.fillStyle="#fff";c.fillText(this.name,180,16);c.restore();f&&(c.font="500 24px Helvetica Neue, Helvetica, Arial, sans-serif",c.fillStyle=0===
a?"#000":"#fff",c.fillText(f[0][0],128,25),c.fillStyle=3===a?"#000":"#fff",c.fillText(f[3]?f[3][0]:"",128,245),c.save(),c.rotate(Math.PI/2),c.fillStyle=2===a?"#000":"#fff",c.fillText(f[2]?f[2][0]:"",128,-10),c.fillStyle=1===a?"#000":"#fff",c.fillText(f[1][0],128,-230),c.restore());c.restore();return this},action:function(a){a=this.ba(a.x,a.y);if(4===a)return location.hash="#/";this.items&&(a=this.items[a])&&(Da.test(a[1])?location.hash="#/"+a[1]:location.href=a[1])},set:function(a){if(this.name!==
a.name){var b;if(this.items)for(var d=this.items.length;d--;)if(this.items[d][0]===a.name){b=d;break}this.direction=void 0===b?3-this.direction:b;this.position=void 0===b?-1:b;this.items=a.items;this.name=a.name;this.ua="Indamix"!==a.name;this.content=a.content}return this},ba:function(a,b){return a!==a?-1:this.ua&&50>Math.abs(a-b)&&120>a+b?4:a>b?256>a+b?0:1:256>a+b?2:3}});var Da=/^[\w-]+$/;Q.a&&(Q=Q.a);var R={};
R.a=C.extend({constructor:function(a,b,d){this.input=b;this.j=d;this.ab=a;this.cb=this.input.getContext("2d");this.Ba=this.j.getContext("2d")},set:function(a){a=a||this.ab;this.Ca=this.Ba.getImageData(0,0,this.j.width,this.j.height);this.da=this.input.width;var b=Array(this.da*this.input.height);b.width=this.input.width;for(var d=b.length;d--;)b[d]=d;this.Da=this.j.width;var d=new ArrayBuffer(this.Da*this.j.height<<1),c=this.jb=new Uint16Array(d);c.width=this.j.width;a(b,c);for(d=b.length;d--;)b[d]=[];
for(d=c.length;d--;)a=c[d],0!==a&&b[a].push(d);this.matrix=b},update:function(){var a=this.input.width,b=this.input.height,d=this.cb.getImageData(0,0,a,b).data,c=this.Ca.data,f=this.matrix,g,h,e,l,k,p;for(g=a;g--;)for(h=b;h--;)for(l=g+h*a,p=f[l],l<<=2,e=0;e<p.length;e++)k=p[e]<<2,c[k]=d[l],c[k+1]=d[l+1],c[k+2]=d[l+2],c[k+3]=d[l+3];this.Ba.putImageData(this.Ca,0,0)},reverse:function(a){var b=this.jb[a.x+a.y*this.Da];0===b?(a.x=NaN,a.y=NaN):(a.x=b%this.da,a.y=(b-a.x)/this.da)}});R.a&&(R=R.a);var S={},Ea=E,Fa=R,Ga=Q,Ha=P,Ia=s.m,Ja=u;
S.a=Ea.extend({constructor:function(a){function b(a){this(a.pageX*c,a.pageY*c)}function d(a){a=a.originalEvent.changedTouches[0];this(a.screenX*c,a.screenY*c);return!1}Ea.call(this,{b:a});a=this.n=$('<canvas class="fullScreen"></canvas>').appendTo(a);var c=this.Q=window.devicePixelRatio||1;1024<window.innerWidth&&(c=this.Q=1);this.w=a[0];var f=$("<canvas></canvas>")[0];f.width=256;f.height=256;this.u=new Fa(this.$a.bind(this),f,this.w);this.m=new Ga(f,Ia[""]);this.transition=new Ha(f.getContext("2d"));
this.c=this.c.bind(this);this.action=this.action.bind(this);this.update=this.update.bind(this);this.tb=this.u.update.bind(this.u);this.cursor={x:NaN,y:NaN};this.ma();$(window).on("resize",Ja.Sa(this.ma.bind(this)));a.on("mouseup",b.bind(this.action)).on("mousemove",b.bind(this.update)).on("touchend",d.bind(this.action)).on("touchmove touchstart",d.bind(this.update))},title:"Indamix",css:!1,sb:["share"],i:function(a){Ea.prototype.i.call(this);$(document.body).addClass("root");this.transition.vb(this.m.getData(),
this.m.set(Ia[a]).c().getData(),500,this.m.direction,this.tb)},s:function(){Ea.prototype.s.call(this);$(document.body).removeClass("root")},action:function(a,b){a&&(this.cursor.x=a,this.cursor.y=b,this.u.reverse(this.cursor),this.m.action(this.cursor))},update:function(a,b){a&&(this.cursor.x=a,this.cursor.y=b,this.u.reverse(this.cursor),cancelAnimationFrame(this.timer),this.timer=requestAnimationFrame(this.c))},c:function(){isNaN(this.cursor.x)?!1!==this.X&&(this.X=!1,this.b.removeClass("actionable")):
!0!==this.X&&(this.X=!0,this.b.addClass("actionable"));this.transition.wa||(this.m.c(this.cursor),this.u.update())},ma:function(){var a=window.innerWidth,b=window.innerHeight;1<this.Q&&this.n.css({width:a,height:b});this.w.width=a*this.Q;this.w.height=b*this.Q;this.u.set();this.c()},B:function(a,b){for(var d=0,c;;){c=Ka.apply(null,a);if(!c)break;var f=a[0],g=a[1],h=a[2],e=a[3],l=c[0],k=c[1],p=c[2],m=c[3],n=b,n=n%4;this.Ha.apply(this,1===n?[l,k,f,g,p,m,h,e]:2===n?[p,m,l,k,h,e,f,g]:3===n?[h,e,p,m,f,
g,l,k]:[f,g,h,e,l,k,p,m]);d%2&&this.B([a[0],a[1],c[0],c[1]],b+1);a=c;d++}},Ha:function(a,b,d,c,f,g,h,e){T.set(d,c,a,b,h,e,f,g);a=this.j;b=this.input;d=a.width;c=256/T.Ta|0;1>c&&(c=1);for(f=0;256>f;f+=c)for(g=0;256>g;g+=c)T(f,g),a[(T.x|0)+(T.y|0)*d]=b[f+256*g]},$a:function(a,b){T.size(256,256);this.input=a;this.j=b;var d=this.w.width>>1,c=this.w.height>>1;this.Ha(d,c+128,d-128,c,d+128,c,d,c-128);this.B([d+128,c,d,c-128],0);this.B([d,c+128,d+128,c],1);this.B([d-128,c,d,c+128],2);this.B([d,c-128,d-128,
c],3)}});function Ka(a,b,d,c){d-=a;var f=c-b;c=0.79*Math.sqrt(d*d+f*f);if(0.5>c)return!1;f=Math.atan2(f,d)-0.53;d=f+Math.PI/2;a+=c*Math.cos(d);b+=c*Math.sin(d);d=a+c*Math.cos(f);c=b+c*Math.sin(f);return[a,b,d,c]}var T=function(){function a(m,n){m/=b;n/=d;var t=c+e*m,A=f+l*m,I=h+p*m;a.x=t+(g+k*m-t)*n;a.y=A+(I-A)*n}var b,d,c,f,g,h,e,l,k,p;a.set=function(b,d,t,A,I,ea,na,oa){c=b;f=d;g=t;h=A;e=I-b;l=ea-d;k=na-t;p=oa-A;a.Ta=Math.sqrt(Math.max(e*e+l*l,k*k+p*p))};a.size=function(a,c){b=a;d=c};return a}();
S.a&&(S=S.a);var U={};
U.a=C.extend({constructor:function(a){for(var b in a)this[b]=a[b];this.M()},M:function(){this.ha=Array(500);for(var a=this.ha.length;a--;)this.ha[a]=Math.random()*Math.PI*2},c:function(a,b){var d=Math.random;b=b/4+this.shift;for(var c=40/Math.abs(b),f=1.2*b+50,c=c*c*c*c,g=b;g<f;g++){var h=g*g*g*1E-6,e=this.ha;1>c&&(h*=c);if(!(0.05>=h)){a.strokeStyle="hsla("+this.color+",100%,"+(0.7*g|0)+"%,"+h+")";a.beginPath();for(h=e.length;0<=h;h-=2){var l=e[h],k=this.x+g*Math.cos(l)*Math.cos(e[h+1])+d(),l=this.y+
g*Math.sin(l)+d()+g*g/700;a.moveTo(k,l);a.lineTo(k+1,l)}a.stroke()}}}});U.a&&(U=U.a);var V={},La=U,Ma=[];
V.a=C.extend({constructor:function(){this.top=0;this.width=window.innerWidth;this.height=window.innerHeight;this.n=$('<canvas id="fx" width="'+this.width+'"height="'+this.height+'"></canvas>').prependTo(document.body);this.d=this.n[0].getContext("2d");for(a=12;a--;)Ma[a]=a/12*360;this.sa=[];for(var a=6;a--;)for(var b=3;b--;)this.sa.push(new La({x:120+120*a+300*b,y:200+200*Math.random(),shift:70-120*a-40*b,color:Ma[(a+3*b)%Ma.length]}));window.addEventListener("resize",this.resize.bind(this));"ontouchstart"in
window?this.c():(window.addEventListener("scroll",this.wb.bind(this)),this.J=this.J.bind(this),this.top=-300,this.J());this.c=this.c.bind(this)},J:function(){this.c();0>this.top&&(this.top+=-0.1*this.top+2,requestAnimationFrame(this.J))},c:function(){var a=this.d,b=this.top,d=this.sa;a.clearRect(0,0,this.width,this.height);for(var c=d.length;c--;)d[c].c(a,b)},wb:function(){this.top=window.scrollY;requestAnimationFrame(this.c)},resize:function(){this.width=window.innerWidth;this.height=window.innerHeight;
this.n.attr("width",this.width).attr("height",this.height);this.c()}});V.a&&(V=V.a);var X={};
X.a=C.extend({constructor:function(a){this.b=a.b;this.V=$('<div class="plug"></div>');this.o=$('<div class="veil"></div>');this.b.on("click","img",this.show.bind(this));this.o.on("click",this.hide.bind(this));this.ga=this.ga.bind(this);this.fa=this.fa.bind(this)},show:function(a){this.h||(this.h=!0,this.U=$(a.target),this.o.appendTo(this.b),this.V.insertAfter(this.U),this.U.appendTo(this.o).css(this.bb()),setTimeout(this.ga,100))},ga:function(){this.o.addClass("show")},hide:function(){if(this.h)return this.h=!1,
this.o.removeClass("show"),this.U.css({width:"",height:""}).insertAfter(this.V),this.V.detach(),setTimeout(this.fa,400),!1},fa:function(){this.o.detach()},bb:function(){var a=window.innerWidth/window.innerHeight,b=1.5<a?window.innerHeight:window.innerWidth/1.5;return{width:Math.min(1.5<a?1.5*window.innerHeight:window.innerWidth,900),height:Math.min(b,600)}}});X.a&&(X=X.a);var Y={},Na=E,Oa=X;Y.a=Na.extend({update:["model",function(a){Na.prototype.update.call(this,a);new Oa({b:this.b})}],v:'{{#projects}}<div class="panel" id="{{name}}"><h2><a href="{{url}}">{{t}}</a></h2><span class="desc">{{desc}}</span><div class="cf"><img src="{{path}}static/i/projects/{{name}}0.{{ext}}"/>{{#list}}<p>{{{1}}}</p>{{/list}}</div><div class="cf tags"><img src="{{path}}static/i/projects/{{name}}1.{{ext}}"/>{{#tags}}<span>{{.}}</span>{{/tags}}</div></div>{{/projects}}'});Y.a&&(Y=Y.a);var Pa={},Qa=E,Ra=Y,Sa=v,Ta=V,Ua=Qa.extend({constructor:["router","tpl","location",function(a,b,d,c){Qa.call(this,{b:c});new Ra({b:this.b.find("#content")});this.fx=new Ta;this.sb=["home","share",$(b('{{#projects}}<a href="'+d.pa()+'/#/projects/{{name}}" style="background:url({{path}}static/i/projects/{{name}}-thumb.png)"></a>{{/projects}}',Sa))]}],v:'<div id="content"></div>',title:"Indamix Projects",css:!1,i:function(a){Qa.prototype.i.call(this);$(document.body).addClass("root").append(this.fx.n);a=$("#"+
a);a=a.length?a.offset().top-10:0;window.scrollTo(0,a)},s:function(){Qa.prototype.s.call(this);this.fx.n.detach();$(document.body).removeClass("root")}});Pa.a=Ua;Pa.a&&(Pa=Pa.a);var Va={},Z=D,Wa=E.constructor,Xa=u,Ya=s;
Va.a=Z.extend({constructor:["router",function(a,b,d){Z.call(this);for(var c=Ya.za.length;c--;)if(Ya.za[0].test(location.pathname))return;window.W&&(window.Jb=require);this.Y=b||{};this.map=d||{};this.H={};this.D=void 0;a.on("route",this.lb,this);this.oa=Xa.aa()+"static/apps/";this.S=this.S.bind(this)}],lb:function(a,b){var d=a[0],c=a[1],f=this.Y[d];f&&!1===(f.prototype?f.prototype.css:f.css)||(this.H[d]||(this.H[d]=Xa.na(this.oa+d)),this.H[d].attr("disabled",!1));var g=function(){if(c&&c.reduce(function(a,
b){return window[b]?a:++a},0))return setTimeout(g,100);$.ajax({dataType:"jsonp",url:this.oa+d+".js",success:this.Ea.bind(this,d,b),C:!0,jsonpCallback:"x"})}.bind(this);f?this.Ea(d,b,f,!0):c?$.when(c.map(function(a){return $.get(this.map[a])}.bind(this))).done(g):g()},Ea:function(a,b,d,c){if(d){var f=this.D!==a;if(f){var g=this.Y[this.D];g&&g.s&&g.s();this.H[this.D]&&this.H[this.D].attr("disabled",!0);this.D=a}!0!==c&&(Wa(d),d=Z.extend(d));"function"===typeof d&&(d=new d($('<div class="container"/>'),
Za));this.Y[a]=d;d.i.apply(d,b);f&&this.trigger("init",d);"function"===typeof d.title?d.title(this.S):this.S(d.title)}},S:function(a){this.title=a;this.trigger("title",a)}});function Za(a){return Z.extend(a,Z)}Za.E=Z;Va.a&&(Va=Va.a);var $a={},ab=D,bb=u,cb=ab.extend({constructor:function(a){ab.call(this);this.O=this.O.bind(this);window.addEventListener("hashchange",this.O,!1);bb.hb(this.O);a&&(this.R=a)},O:function(){for(var a=location.hash.substr(2),b,d,c=0;c<this.R.length&&!(b=this.R[c],d=a.match(b[0]));++c);d&&this.trigger("route",b.slice(1),d.slice(1))}});$a.a=cb;$a.a&&($a=$a.a);var db={},eb=u,fb=$a,gb=Va,hb=Pa,ib=S,jb=O,kb=M,lb=z,mb=v,nb=s,ob=C.extend({constructor:function(){window.W||(window.console={log:function(){}},eb.Pa());ob.F({location:eb.fb,router:new fb(nb.R),tpl:ca.c,model:mb}).F({loader:(new gb({"":ib,tag:jb,projects:hb},nb.map)).on("title",function(a){document.title=a})});new lb(document.body);new kb({b:$('<div id="sidebar"/>').prependTo(document.body),Z:["home","share"]});eb.na(nb.eb);eb.xb()}});db.a=ob;db.a&&(db=db.a);var pb=db;$(function(){new pb});})();
